version: "3"
services:
  frontend:
    image: wirvsvirusarvato/webapp:latest
    ports:
      - 80:80

  server:
    image: wirvsvirusarvato/server:latest
    ports:
      - 8080:8080
    command: ["/wait-for-postgres", "db", "java", "-jar", "-Dspring.profiles.active=prod", "/corona-app.jar"]

  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: corona-app
    volumes:
      - coronaapp:/var/lib/postgresql/data
      
  backend:
    image: wirvsvirusarvato/backend
    environment:
      DATABASE_URL: mysql://myuser:mypassword@mariadb:3306/quarantaenehelfer?serverVersion=5.7
      SERVICE_URL: http://server:8080
      
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: quarantaenehelfer
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      
volumes:
  coronaapp:
