version: "3"
services:
  frontend:
    image: wirvsvirusarvato/webapp:latest
    ports:
      - 80:80

  server:
    image: wirvsvirusarvato/server:latest
    ports:
      - 8080:8080

  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: corona-app
    volumes:
      - coronaapp:/var/lib/postgresql/data

volumes:
  coronaapp: